setxkbmap -option caps:escape
# set monitor
xrandr --output HDMI-0 --off --output DVI-I-1 --mode 1680x1050 --pos 1050x0 --rotate normal --output DVI-I-0 --off --output DP-1 --off --output DP-0 --mode 1680x1050 --pos 0x0 --rotate left

exec i3

